# Site settings
title: Natural Intelligence
email: greydanus.17(at)gmail.com
description: "A science blog by Sam Greydanus"
baseurl: ""
url: "http://greydanus.github.io"
twitter_username: samgreydanus
github_username: greydanus
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge